export default {
  image1: require('../assets/images/profile_images/1.png'),
  image2: require('../assets/images/profile_images/2.png'),
  image3: require('../assets/images/profile_images/3.png'),
  image4: require('../assets/images/profile_images/4.png'),
  image5: require('../assets/images/profile_images/5.png'),
  image6: require('../assets/images/profile_images/6.png'),
  image7: require('../assets/images/profile_images/7.png'),
  image8: require('../assets/images/profile_images/8.png'),
  image9: require('../assets/images/profile_images/9.png'),
  image10: require('../assets/images/profile_images/10.png'),
  image11: require('../assets/images/profile_images/11.png'),
  image12: require('../assets/images/profile_images/12.png'),
  image13: require('../assets/images/profile_images/13.png'),
  image14: require('../assets/images/profile_images/14.png'),
  image15: require('../assets/images/profile_images/15.png'),
  image16: require('../assets/images/profile_images/16.png'),
  image17: require('../assets/images/profile_images/17.png'),
  image18: require('../assets/images/profile_images/18.png'),
  image19: require('../assets/images/profile_images/19.png'),
  image20: require('../assets/images/profile_images/20.png'),
};
